import app from "../../server.js";
import activity_log from "../api/activity_log/routes/activity_log.js";
import address from "../api/address/routes/address.js";
import admin from "../api/admin/routes/admin.js";
import banner from "../api/banner/routes/banner.js";
import campaign from "../api/campaign/routes/campaign.js";
import cart from "../api/cart/routes/cart.js";
import category from "../api/category/routes/category.js";
import collection from "../api/collection/routes/collection.js";
import custom_courier from "../api/custom_courier/routes/custom_courier.js";
import global from "../api/global/routes/global.js";
import global_brand from "../api/global_brand/routes/global_brand.js";
import group from "../api/group/routes/group.js";
import lead from "../api/lead/routes/lead.js";
import order from "../api/order/routes/order.js";
import order_variant from "../api/order_variant/routes/order_variant.js";
import payment_log from "../api/payment_log/routes/payment_log.js";
import permission from "../api/permission/routes/permission.js";
import product from "../api/product/routes/product.js";
import product_metrics from "../api/product_metrics/routes/product_metrics.js";
import privacy_policy from "../api/privacy_policy/routes/privacy_policy.js";
import role from "../api/role/routes/role.js";
import server_subscription from "../api/server_subscription/routes/server_subscription.js";
import ship_rocket_order from "../api/ship_rocket_order/routes/ship_rocket_order.js";
import ship_rocket_orderitem from "../api/ship_rocket_orderitem/routes/ship_rocket_orderitem.js";
import policy from "../api/policy/routes/policy.js";
import setting from "../api/setting/routes/setting.js";
import support_ticket from "../api/support_ticket/routes/support_ticket.js";
import user from "../api/user/routes/user.js";
import sub_category from "../api/sub_category/routes/sub_category.js";
import tag from "../api/tag/routes/tag.js";
import transaction from "../api/transaction/routes/transaction.js";
import upload from "../api/upload/routes/upload.js";
import variant from "../api/variant/routes/variant.js";
import wallet from "../api/wallet/routes/wallet.js";
import ship_rocket_return from "../api/ship_rocket_return/routes/ship_rocket_return.js";
import notification from "../api/notification/routes/notification.js";
import product_policy from "../api/product_policy/routes/product_policy.js";
import promotional_message from "../api/promotional_message/routes/promotional_message.js";
import testimonial from "../api/testimonial/routes/testimonial.js";
import story from "../api/story/routes/story.js";
import return_order from "../api/return_order/routes/return_order.js";
import product_review from "../api/product_review/routes/product_review.js";
import marquee from "../api/marquee/routes/marquee.js"
import coupon from "../api/coupon/routes/coupon.js";

activity_log(app);
address(app);
admin(app);
banner(app);
campaign(app);
cart(app);
category(app);
collection(app);
custom_courier(app);
global(app);
global_brand(app);
global_brand(app);
group(app);
lead(app);
order(app);
order_variant(app);
payment_log(app);
permission(app);
product(app);
product_metrics(app);
privacy_policy(app);
role(app);
server_subscription(app);
ship_rocket_order(app);
ship_rocket_orderitem(app);
payment_log(app);
policy(app);
setting(app);
support_ticket(app);
user(app);
sub_category(app);
tag(app);
transaction(app);
upload(app);
user(app);
variant(app);
wallet(app);
ship_rocket_return(app);
notification(app);
activity_log(app);
product_policy(app);
promotional_message(app);
testimonial(app);
story(app);
return_order(app);
product_review(app);
marquee(app);
coupon(app);